// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxve3aO5o1gkcxCs0hKTTJiKAgBiUuB0A',
    appId: '1:645872138343:web:1ebd1c95b871e8dde3fcc2',
    messagingSenderId: '645872138343',
    projectId: 'shoppingapp-fa747',
    authDomain: 'shoppingapp-fa747.firebaseapp.com',
    storageBucket: 'shoppingapp-fa747.firebasestorage.app',
    measurementId: 'G-HWZNVMRK45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDifgxFx1cgbfOaZyR22ATYIECsgGHqS3Q',
    appId: '1:645872138343:android:2a8dcbc200c5b4afe3fcc2',
    messagingSenderId: '645872138343',
    projectId: 'shoppingapp-fa747',
    storageBucket: 'shoppingapp-fa747.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgFKPWvBtB-ebtM5A9SXmM8OKf3GY8_rY',
    appId: '1:645872138343:ios:53deef5c36f2e6c9e3fcc2',
    messagingSenderId: '645872138343',
    projectId: 'shoppingapp-fa747',
    storageBucket: 'shoppingapp-fa747.firebasestorage.app',
    iosBundleId: 'com.example.shopadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxve3aO5o1gkcxCs0hKTTJiKAgBiUuB0A',
    appId: '1:645872138343:web:565144bdb364bcaae3fcc2',
    messagingSenderId: '645872138343',
    projectId: 'shoppingapp-fa747',
    authDomain: 'shoppingapp-fa747.firebaseapp.com',
    storageBucket: 'shoppingapp-fa747.firebasestorage.app',
    measurementId: 'G-W5EP72YKK0',
  );
}
